
[window]
opacity = 0.8
decorations = "Full"
decorations_theme_variant = "Dark"
padding.x = 5
padding.y = 5

[font]
size = 15.0

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true  # Auto-hide cursor while typing


